version: '3.4'

services:
  proxy:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
      args:
        - INSTALL_ADDONS=true
    image: s3-hooked/proxy:prod
    environment:
      - PROXY_SECRET
      - PROXY_OBJECT_STORE_HOST=${PROXYO_OBJECT_STORE_HOST:-minio}
      - PROXY_OBJECT_STORE_PORT=${PROXYO_OBJECT_STORE_PORT:-9000}
      - PROXY_OBJECT_STORE_SSL_ENABLED=${PROXY_OJECT_STORE_SSL_ENABLED:-true}
    ports:
      - "8080:8000"
  minio:
    image: minio/minio:RELEASE.2023-09-16T01-01-47Z
    volumes:
      - minio_data:/data
    command: server data

volumes:
  minio_data:

